# Generated by Django 4.2.5 on 2023-10-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descripction',
            new_name='description',
        ),
    ]
